name: AQICN Scraper

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt

      - run: python scraper.py
        env:
          IQAIR_API_KEY: ${{ secrets.IQAIR_API_KEY }}

      - name: Commit CSV
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add aqicn.csv

          git diff --cached --quiet || git commit -m "Update AQI"

          git push